import Handlebars from 'handlebars';
import { type ConfigManager } from '../config/config-manager';
import { type Db } from '../config/db';
import { type DbLogger } from '../config/db';
import { parseDnsmasqLeases, type DhcpLease } from './lease-parser';

/**
 * DHCP server management for the TNC network (T35).
 *
 * Generates dnsmasq configuration bound only to the TNC interface, enabling DHCP
 * services for CNC machines. Static reservations are read from the `tnc_clients`
 * table; discovered machines are persisted in the `discovered_machines` table
 * (when it exists) or returned in-memory.
 *
 * Critical invariant: dnsmasq never listens on the LAN interface.
 */

// ---------------------------------------------------------------------------
// Configuration generation
// ---------------------------------------------------------------------------

export interface DnsmasqConfig {
  readonly tncInterface: string;
  readonly rangeStart: string;
  readonly rangeEnd: string;
  readonly leaseTime: string; // e.g., "12h"
  readonly gateway: string;
  readonly dns: string; // single IP or multiple space-separated
  readonly domain: string;
  readonly enabled: boolean;
}

interface StaticReservation {
  readonly mac: string;
  readonly ip: string;
  readonly hostname: string;
}

const DNSMASQ_TEMPLATE = `# Generated by TNC Network Bridge — DHCP server for the TNC network segment
# This configuration binds ONLY to the {{tncInterface}} interface.
# Changes made via the web UI overwrite this file.

{{#if tncInterface}}
# Bind only to the TNC-side interface; never listen on the LAN
interface={{tncInterface}}
bind-interfaces
{{/if}}

# DHCP range and timing
dhcp-range={{rangeStart}},{{rangeEnd}},{{leaseTime}}

# Gateway and DNS
dhcp-option=option:router,{{gateway}}
dhcp-option=option:dns-server,{{dns}}
dhcp-option=option:domain-name,{{domain}}

# Static reservations
{{#each reservations}}
dhcp-host={{mac}},{{ip}},{{hostname}}
{{/each}}

# Logging configuration
log-dhcp
log-facility=/dev/null
`;

const template = Handlebars.compile(DNSMASQ_TEMPLATE, { noEscape: true, strict: false });

/**
 * Renders a dnsmasq configuration from the given parameters.
 *
 * Does not validate the parameters — that is the caller's responsibility via the
 * config schema and the privileged helper (which runs `dnsmasq -C --test` before activation).
 */
export function renderDnsmasqConf(
  config: DnsmasqConfig,
  reservations: readonly StaticReservation[],
): string {
  const view = {
    tncInterface: config.tncInterface,
    rangeStart: config.rangeStart,
    rangeEnd: config.rangeEnd,
    leaseTime: config.leaseTime,
    gateway: config.gateway,
    dns: config.dns,
    domain: config.domain,
    reservations: reservations.map((r) => ({
      mac: r.mac.toLowerCase(),
      ip: r.ip,
      hostname: r.hostname || r.mac.replace(/:/g, '-'),
    })),
  };

  return template(view);
}

// ---------------------------------------------------------------------------
// Manager class
// ---------------------------------------------------------------------------

export interface DHCPConfigManagerOptions {
  readonly db: Db;
  readonly config: ConfigManager;
  readonly logger?: DbLogger;
}

export class DHCPConfigManager {
  private readonly db: Db;
  private readonly config: ConfigManager;
  private readonly logger: DbLogger | undefined;

  constructor(options: DHCPConfigManagerOptions) {
    this.db = options.db;
    this.config = options.config;
    this.logger = options.logger;
  }

  /**
   * Builds the complete dnsmasq configuration by combining settings and static reservations.
   *
   * Reads from the `dhcp` config section and the `tnc_clients` table.
   */
  buildConfiguration(tncInterface: string): { config: DnsmasqConfig; content: string } {
    const dhcpConfig = this.config.get('dhcp');
    const networkConfig = this.config.get('network');

    // If TNC interface is not provided, infer from network config
    const interface_ = tncInterface || networkConfig.tnc.interface;

    // Parse the range to extract start and end
    const rangeParts = dhcpConfig.range.split('-');
    const rangeStart = rangeParts[0] || dhcpConfig.range;
    const rangeEnd = rangeParts[1] || dhcpConfig.range;

    const config: DnsmasqConfig = {
      tncInterface: interface_,
      rangeStart,
      rangeEnd,
      leaseTime: dhcpConfig.leaseTime,
      gateway: dhcpConfig.gateway || this.extractGatewayFromTncInterface(networkConfig.tnc.address),
      dns: dhcpConfig.dns,
      domain: 'tnc.local',
      enabled: dhcpConfig.enabled,
    };

    // Fetch static reservations from tnc_clients table
    const reservations = this.getStaticReservations();

    const content = renderDnsmasqConf(config, reservations);
    return { config, content };
  }

  /**
   * Extracts the gateway IP from the TNC interface CIDR address.
   * Example: "192.168.42.1/24" -> "192.168.42.1"
   */
  private extractGatewayFromTncInterface(address: string): string {
    const cidr = address.split('/')[0] || address;
    return cidr;
  }

  /**
   * Fetches static reservations from the `tnc_clients` table.
   */
  private getStaticReservations(): StaticReservation[] {
    try {
      const rows = this.db.all<{ mac_address: string; reserved_ip: string; name: string }>(
        `SELECT mac_address, reserved_ip, name FROM tnc_clients
         WHERE mac_address IS NOT NULL AND reserved_ip IS NOT NULL AND dhcp_reserved = 1`,
      );

      return rows
        .filter((row) => row.mac_address && row.reserved_ip)
        .map((row) => ({
          mac: row.mac_address,
          ip: row.reserved_ip,
          hostname: row.name || row.mac_address.replace(/:/g, '-'),
        }));
    } catch {
      // Table may not exist yet or column names differ
      return [];
    }
  }

  /**
   * Parses the dnsmasq lease file to discover machines.
   *
   * Returns the list of active leases. If the file does not exist, returns an empty list.
   */
  async parseLeaseFile(leaseFilePath = '/var/lib/dnsmasq/dnsmasq.leases'): Promise<DhcpLease[]> {
    try {
      const fs = await import('node:fs/promises');
      const content = await fs.readFile(leaseFilePath, 'utf-8');
      return parseDnsmasqLeases(content);
    } catch (error) {
      // File not found or read error — log and return empty
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        this.logger?.warn({ err: error, path: leaseFilePath }, 'could not read dnsmasq lease file');
      }
      return [];
    }
  }

  /**
   * Updates the `discovered_machines` table with machines from DHCP leases and SMB sessions.
   *
   * If the `discovered_machines` table does not exist, this is a no-op.
   */
  async updateDiscoveredMachines(leases: readonly DhcpLease[]): Promise<void> {
    // Check if the table exists
    const tableExists = this.db.get(
      `SELECT 1 FROM sqlite_master WHERE type='table' AND name='discovered_machines'`,
    );

    if (!tableExists) {
      return;
    }

    const now = Math.floor(Date.now() / 1000);

    this.db.transaction(() => {
      for (const lease of leases) {
        const existing = this.db.get<{ id: number }>(
          `SELECT id FROM discovered_machines WHERE mac_address = @mac`,
          { mac: lease.mac },
        );

        if (existing) {
          this.db.run(
            `UPDATE discovered_machines
             SET ip_address = @ip, hostname = @hostname, last_seen = @now, is_online = 1
             WHERE mac_address = @mac`,
            {
              ip: lease.ip,
              hostname: lease.hostname,
              now,
              mac: lease.mac,
            },
          );
        } else {
          this.db.run(
            `INSERT INTO discovered_machines (mac_address, ip_address, hostname, last_seen, is_online, dhcp_leased)
             VALUES (@mac, @ip, @hostname, @now, 1, 1)`,
            {
              mac: lease.mac,
              ip: lease.ip,
              hostname: lease.hostname,
              now,
            },
          );
        }
      }
    });
  }

  /**
   * Reads discovered machines from the `discovered_machines` table.
   *
   * Returns an empty array if the table does not exist.
   */
  getDiscoveredMachines(): Array<{
    readonly mac: string;
    readonly ip: string;
    readonly hostname: string;
    readonly lastSeen: number;
    readonly isOnline: boolean;
  }> {
    // Check if the table exists
    const tableExists = this.db.get(
      `SELECT 1 FROM sqlite_master WHERE type='table' AND name='discovered_machines'`,
    );

    if (!tableExists) {
      return [];
    }

    const rows = this.db.all<{
      mac_address: string;
      ip_address: string;
      hostname: string;
      last_seen: number;
      is_online: number;
    }>(`SELECT mac_address, ip_address, hostname, last_seen, is_online FROM discovered_machines`);

    return rows.map((row) => ({
      mac: row.mac_address,
      ip: row.ip_address,
      hostname: row.hostname,
      lastSeen: row.last_seen,
      isOnline: row.is_online === 1,
    }));
  }
}
