/**
 * Shared `auth.log` fixture.
 *
 * Consumed by two tests that must never disagree:
 *  - T6 checks that the writer produces these lines.
 *  - T37 checks that the shipped Fail2Ban filter matches them, using `fail2ban-regex`.
 *
 * The lines are written out literally rather than generated by the formatter. That is
 * the point — if someone changes the format, the formatter and its own test would move
 * together and the change would go unnoticed. These are frozen samples of what is on
 * disk today, and Fail2Ban's contract is with the file, not with our code.
 */

export interface AuthLogSample {
  readonly description: string;
  readonly line: string;
  /** Whether the Fail2Ban failregex must count this line as a failure. */
  readonly shouldMatch: boolean;
  /** The address Fail2Ban must extract, when it matches. */
  readonly expectedHost?: string;
}

export const AUTH_LOG_SAMPLES: readonly AuthLogSample[] = [
  {
    description: 'a wrong password from an IPv4 address',
    line: '2026-09-07T14:23:11.482+02:00 tnc-bridge[1287]: authentication failure for user "admin" from 192.168.1.50 (reason: invalid_password)',
    shouldMatch: true,
    expectedHost: '192.168.1.50',
  },
  {
    description: 'an unknown user',
    line: '2026-09-07T14:23:14.902+02:00 tnc-bridge[1287]: authentication failure for user "root" from 192.168.1.50 (reason: unknown_user)',
    shouldMatch: true,
    expectedHost: '192.168.1.50',
  },
  {
    description: 'a failure with no reason recorded',
    line: '2026-09-07T14:23:19.117+02:00 tnc-bridge[1287]: authentication failure for user "admin" from 10.0.0.7',
    shouldMatch: true,
    expectedHost: '10.0.0.7',
  },
  {
    description: 'a failure from an IPv6 address',
    line: '2026-09-07T14:24:02.004+02:00 tnc-bridge[1287]: authentication failure for user "admin" from 2001:db8::42 (reason: invalid_password)',
    shouldMatch: true,
    expectedHost: '2001:db8::42',
  },
  {
    description: 'an empty username, which a malformed client can send',
    line: '2026-09-07T14:24:30.771+02:00 tnc-bridge[1287]: authentication failure for user "" from 192.168.1.99 (reason: unknown_user)',
    shouldMatch: true,
    expectedHost: '192.168.1.99',
  },
  {
    description: 'a rejected API token',
    line: '2026-09-07T14:25:01.233+02:00 tnc-bridge[1287]: authentication failure for user "token" from 192.168.1.77 (reason: invalid_token)',
    shouldMatch: true,
    expectedHost: '192.168.1.77',
  },

  // Negatives — matching any of these would ban legitimate users.
  {
    description: 'a successful login',
    line: '2026-09-07T14:26:00.010+02:00 tnc-bridge[1287]: accepted login for user "admin" from 192.168.1.50',
    shouldMatch: false,
  },
  {
    description: 'a logout',
    line: '2026-09-07T14:40:00.010+02:00 tnc-bridge[1287]: session closed for user "admin" from 192.168.1.50',
    shouldMatch: false,
  },
  {
    description: 'the informational lockout notice',
    line: '2026-09-07T14:23:25.500+02:00 tnc-bridge[1287]: too many authentication failures for user "admin" from 192.168.1.50',
    shouldMatch: false,
  },
  {
    description: 'a forged line embedded in a username, which must not be counted twice',
    line: '2026-09-07T14:27:00.000+02:00 tnc-bridge[1287]: authentication failure for user "admin_ from 8.8.8.8 _" from 192.168.1.50 (reason: invalid_password)',
    shouldMatch: true,
    // The address must come from the real field, never from the attacker-controlled one.
    expectedHost: '192.168.1.50',
  },
  {
    description: 'an unrelated line from another service',
    line: '2026-09-07T14:28:00.000+02:00 sshd[999]: Failed password for admin from 192.168.1.50 port 22 ssh2',
    shouldMatch: false,
  },
  {
    description: 'a sync log line that happens to mention a failure',
    line: '2026-09-07T14:29:00.000+02:00 tnc-bridge[1287]: transfer failure for programs/part1.h from 192.168.1.50',
    shouldMatch: false,
  },
];

/** Just the lines, in file order — what a test writes into a scratch auth.log. */
export const AUTH_LOG_FILE_CONTENT = `${AUTH_LOG_SAMPLES.map((s) => s.line).join('\n')}\n`;

/** How many of the samples Fail2Ban must count. */
export const EXPECTED_MATCH_COUNT = AUTH_LOG_SAMPLES.filter((s) => s.shouldMatch).length;
