import { INTERFACE_NAME_PATTERN } from '../../shared';

/**
 * The baseline ruleset: the management surface must never answer on the TNC segment.
 *
 * The bridge exists to put an SMB1 island in front of machines that cannot do anything
 * better. Everything on that island is, by construction, a device nobody can patch —
 * which makes it the last place the appliance's own admin interface should be
 * reachable from. The device is configured from the LAN, and only from the LAN.
 *
 * This is enforced at two levels on purpose. nftables here is the real barrier: it
 * matches on the *interface*, so it keeps holding when either side's address changes,
 * and it drops the packet before Node ever sees it. `management-guard.ts` is the
 * backstop for the case where this ruleset is not in force — someone running
 * `nft flush ruleset` to debug something else should not silently expose the UI.
 *
 * Binding the listener to the LAN address instead was the obvious third option and is
 * deliberately not used: the LAN address may be handed out by DHCP, may not exist yet
 * when the service starts, and changes under exactly the operation (`apply-network`)
 * that most needs the management interface to stay up.
 */

/** nftables table name. Ours alone; nothing else in the system may write to it. */
export const FIREWALL_TABLE = 'tnc_bridge';

/**
 * Ports that configure the device.
 *
 * SSH is in the list because the requirement is that the appliance is configured from
 * the LAN, and a shell is a configuration channel — leaving 22 open on the machine
 * segment would satisfy the letter of "the web interface is not reachable" while
 * missing its point.
 */
export const MANAGEMENT_PORTS = [22, 443] as const;

export class FirewallError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'FirewallError';
  }
}

export interface ManagementIsolationInput {
  /** Interface facing the machines. Everything arriving here is untrusted. */
  readonly tncInterface: string;
  readonly managementPorts?: readonly number[];
}

/**
 * Renders the ruleset.
 *
 * The policy is `accept`, matching `security.firewallDefault`'s documented default: the
 * bridge sits inside a plant network and is not a perimeter device, so this adds one
 * targeted drop rather than taking over the host's filtering.
 */
export function renderManagementIsolation(input: ManagementIsolationInput): string {
  const iface = input.tncInterface;
  // The name is interpolated into a config file that runs as root. It comes from our own
  // validated config, but a value that reached here another way must not be able to
  // close the quote and append a rule.
  if (!INTERFACE_NAME_PATTERN.test(iface)) {
    throw new FirewallError(`Refusing to build a ruleset for the interface name "${iface}"`);
  }

  const ports = [...(input.managementPorts ?? MANAGEMENT_PORTS)].sort((a, b) => a - b);
  if (ports.length === 0) {
    throw new FirewallError('A management isolation ruleset with no ports would do nothing');
  }
  for (const port of ports) {
    if (!Number.isInteger(port) || port < 1 || port > 65_535) {
      throw new FirewallError(`Not a TCP port: ${String(port)}`);
    }
  }

  return `#!/usr/sbin/nft -f
# Generated by TNC Network Bridge. Do not edit; changes are overwritten.
#
# The management interface answers on the LAN only. The TNC segment carries machines
# running SMB1 because they cannot run anything newer, and none of them has any business
# reaching this appliance's configuration.
#
# Declaring the table before deleting it is the idempotent create-or-replace idiom:
# 'delete' on a table that does not exist is an error, and the bare declaration makes
# sure it exists first. Without it, loading this file on a fresh boot would fail.
table inet ${FIREWALL_TABLE}
delete table inet ${FIREWALL_TABLE}

table inet ${FIREWALL_TABLE} {
  chain input {
    # accept, not drop: this bridge is not a perimeter firewall, and a default-deny
    # policy here would silently break SMB, DHCP and DNS on the machine segment — the
    # three things the appliance exists to serve.
    type filter hook input priority filter; policy accept;

    iifname "${iface}" tcp dport { ${ports.join(', ')} } drop
  }
}
`;
}

/**
 * True when a ruleset that isolates management on `tncInterface` is already loaded.
 *
 * Compared as text against what we would generate, because the question being asked is
 * "is the current file the one this build produces" — a ruleset edited by hand, or left
 * behind by an older release naming a different interface, both need replacing.
 */
export function isManagementIsolationCurrent(
  loaded: string | undefined,
  input: ManagementIsolationInput,
): boolean {
  return loaded?.trim() === renderManagementIsolation(input).trim();
}
